### ISSUE TITLE
jetton not verify, what's means?

### ISSUE THREAD

**Issue by zy166317** [tonkeeper/ton-assets#1011]
![image](https://github.com/user-attachments/assets/2dc31d2b-ccb0-4ca4-99cd-a7136cd99f39)

**Comment by ghost** [comment]
Yes

**Comment by mahsa6567** [comment]
Yes

🙂

**Comment by mahsa6567** [comment]
###

**Comment by mahsa6567** [comment]
#10-11

**Comment by mahsa6567** [comment]
#1011

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
> ![image](https://github.com/user-attachments/assets/2dc31d2b-ccb0-4ca4-99cd-a7136cd99f39)
> 

https://github.com/tonkeeper/ton-assets/issues/1011

**Comment by Pavelartsmart** [comment]
И что ответили что ни будь?
