### ISSUE TITLE
My workflow need approval, thanks

### ISSUE THREAD

**Issue by GaodeCoin** [tonkeeper/ton-assets#1024]
I added a new token here, but it's told that approval is needed, so please help me , thanks

**Comment by Tonytech-wq** [comment]
@GaodeCoin Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://allchainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Sashastreet3** [comment]
خوبه
