### ISSUE TITLE
Ton

### ISSUE THREAD

**Issue by UkkuJirkova** [tonkeeper/ton-assets#1033]
_Originally posted by @abooodabdlaa in https://github.com/tonkeeper/wallet-api/issues/69_

**Comment by abooodabdlaa** [comment]
yas

**Comment by Jimmy-12344780** [comment]
How i can swap?

**Comment by Khan-arsh** [comment]
@Jimmy-12344780 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Jimmy-12344780** [comment]
Ok

**Comment by abooodabdlaa** [comment]
yas

**Comment by Nwachimereze1-hub** [comment]
> _Originally posted by @abooodabdlaa in [tonkeeper/wallet-api#69](https://github.com/tonkeeper/wallet-api/issues/69)_
