### ISSUE TITLE
We're preparing to the DEX, need your approval

### ISSUE THREAD

**Issue by GaodeCoin** [tonkeeper/ton-assets#1034]
My jetton has been kept by sevral hundreds of wallet and I pulled request to your github.Now, I got some progress to the dex, every thing became more quickly, I'm so sorry to bother you,but I really need your approval, thanks so much

**Comment by Khan-arsh** [comment]
@GaodeCoin Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by ghost** [comment]
signature: 46bf27e6dc6a9506317f87858da2af4acbbb51b2b6e2d6d0c633f13a2bb34bb6e22ecbb7b05eef4ee7037d53e95c5c40f37f7bc9a4902cc7221b0ec92b5c090b
subwallet_id: 698983191
valid_until: 1722450434
seqno: 17
op: 0
payload:
  - mode: 3
    message:
      sum_type: MessageInternal
      message_internal:
        ihr_disabled: true
        bounce: false
        bounced: false
        src: ""
        dest: 0:a1376e8bf9f266ec7c6b11ce6e5cd02a9bda363b9ea888a2e239d2383572bc9a
        value:
          grams: "125000000000"
          other: {}
        ihr_fee: "0"
        fwd_fee: "0"
        created_lt: 0
        created_at: 0
        init: null
        body:
          is_right: false
          value:
            sum_type: TextComment
            op_code: 0
            value:
              text: "521322"

**Comment by ghost** [comment]
521322
