### ISSUE TITLE
Добавить новый жетон ТОН

### ISSUE THREAD

**Issue by Artur4ik79** [tonkeeper/ton-assets#1078]
Получил из проекта ,,Догз,, монеты Тон 
![Screenshot_2024-09-11-22-18-25-826_org telegram messenger](https://github.com/user-attachments/assets/bffc9a9e-9429-4b0b-835e-15fa87f49707)

**Comment by Firontiu** [comment]
> Получил из проекта ,,Догз,, монеты Тон ![Screenshot_2024-09-11-22-18-25-826_org telegram messenger](https://private-user-images.githubusercontent.com/181277612/366599188-bffc9a9e-9429-4b0b-835e-15fa87f49707.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNjYyNjksIm5iZiI6MTcyNjI2NTk2OSwicGF0aCI6Ii8xODEyNzc2MTIvMzY2NTk5MTg4LWJmZmM5YTllLTk0MjktNGIwYi04MzVlLTE1ZmE4N2Y0OTcwNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QyMjE5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTcwMzM0NGMyZDdmNzQ3YzgxMDZjMzE2YjIzMzRmMzlkMWI0ZjY3OGI4OGE2YWNhYzY2NGY4ZTVkN2JmOTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fDF_yNaw8RvEQxtDT8qb2vEk8-awRlmj407GzXp4Nr4)

**Comment by Artur4ik79** [comment]
> > Получил из проекта ,,Догз,, монеты Тона![Скриншот_2024-09-11-22-18-25-826_org мессенджер телеграмм](https://private-user-images.githubusercontent.com/181277612/366599188-bffc9a9e-9429-4b0b-835e-15fa87f49707.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNjYyNjksIm5iZiI6MTcyNjI2NTk2OSwicGF0aCI6Ii8xODEyNzc2MTIvMzY2NTk5MTg4LWJmZmM5YTllLTk0MjktNGIwYi04MzVlLTE1ZmE4N2Y0OTcwNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QyMjE5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTcwMzM0NGMyZDdmNzQ3YzgxMDZjMzE2YjIzMzRmMzlkMWI0ZjY3OGI4OGE2YWNhYzY2NGY4ZTVkN2JmOTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fDF_yNaw8RvEQxtDT8qb2vEk8-awRlmj407GzXp4Nr4)

Не открывается?Что там за ссылка?

**Comment by abooodabdlaa** [comment]
yas

**Comment by abooodabdlaa** [comment]
UQAUisz8Q-j-FBR8knXAWv0zjTs5FkaHmzK62atNQKoyN8CD
