### ISSUE TITLE
Add Token DILS

### ISSUE THREAD

**Issue by VladiCoen** [tonkeeper/ton-assets#1089]
name: Democratic Digital Shekels
description: DILS - The New Internet Meme Currency! 💎 Ready to be part of the new internet phenomenon? Introducing $DILS, the meme token that will change the way you think about cryptocurrency! $DILS - is not just freedom, it’s a lifestyle!
image: https://raw.githubusercontent.com/DDS-Meme/website/main/dilisium.png
address: EQAx_cAYW0Npz0WL8nCQJGMtQXQdtibCqMoUGBiTXM_mZLlv
symbol: DILS
social:
  - "https://t.me/dilscoin"
  - "https://x.com/DILScoin"

**Comment by mahdi1983136** [comment]
> name: DILS description: Democratic Digital Shekels ($DILS): The New Internet Meme Currency! 💎 Ready to be part of the new internet phenomenon? Introducing $DILS, the meme token that will change the way you think about cryptocurrency! $DILS - is not just freedom, it’s a lifestyle! image: https://raw.githubusercontent.com/DDS-Meme/website/main/dilisium.png address: EQAx_cAYW0Npz0WL8nCQJGMtQXQdtibCqMoUGBiTXM_mZLlv symbol: DILS social:
> 
> * "https://t.me/dilscoin"
> * "https://x.com/DILScoin"

UQBpAl7FzjfddyGa12MUxk7NnKwB717-4D-bmEFOug2CJFxS
