### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by VladiCoen** [tonkeeper/ton-assets#1113]
yaml.scanner.ScannerError: mapping values are not allowed here
  in "jettons/DILS.yaml", line 2, column 48
Error: Process completed with exit code 1.

Can you please help with this error?

**Comment by VladiCoen** [comment]
@grishkanaruzhka Hi, can you help me please

**Comment by ghost** [comment]
I don't know how to patch or merge can you help me? I need step by step
guide.
