### ISSUE TITLE
Making a request pull 

### ISSUE THREAD

**Issue by Mhfiz8** [tonkeeper/ton-assets#1128]
I want to transfer 12,552 or so Dogs to my bybit account
![Screenshot_2024-09-26-19-46-23-596_com ton_keeper](https://github.com/user-attachments/assets/0027d4a7-f0d7-4755-92a7-29b2b95a7b36)
, but ton-keeper keeps saying unverified token.

**Comment by M1379M** [comment]
I want to transfer hamester to account
but ton-keeper keeps saying unverified token
