### ISSUE TITLE
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

### ISSUE THREAD

**Issue by Alexforestaneev** [tonkeeper/ton-assets#113]
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

_Originally posted by @DanIsNearby in https://github.com/tonkeeper/ton-assets/pull/108_

**Comment by Ppksu69** [comment]
name: Tali jetton
description: Private bank jetton
image: https://ppksu69.github.io/Logo/IMG_20240109_072013.png
address: EQAqHDLa9tfgvLPV9lyhQMei3uhd4Ic1qFcrbWliLn-Sm3H4
symbol: TALI
max_supply: 1000000
social:
  - https://t.me/talijetton_chat
