### ISSUE TITLE
Unable to transfer assets 

### ISSUE THREAD

**Issue by charis03202** [tonkeeper/ton-assets#1135]
Hi good afternoon sir/ma
I have a complaint about the Tonkeeper app,
I have been trying to transfer my hmstr assets since early this morning to another account but it keeps failing despite the 0.1ton in it and after it fails it reduces 0.001 ton per failed transaction for more than 10 times already 
Please help me out 
I’m extremely tired and frustrated, I keep losing money without getting my money 
![IMG_6256](https://github.com/user-attachments/assets/6c6b264c-8039-4e35-a8fc-da80dde979e2)
![IMG_6252](https://github.com/user-attachments/assets/76d10ba9-6ee9-4c17-83de-253899a1ce68)

**Comment by Sanya19940807** [comment]
![Screenshot_20240928_185528_Tonkeeper](https://github.com/user-attachments/assets/886ff9c7-b257-4e69-8955-b1f309dba486)
 Почему пишет непровереный токен ??? Как такое может быть ,комиссию заберат а токен hmstr не переводит???
