### ISSUE TITLE
Hmstr

### ISSUE THREAD

**Issue by Sanya19940807** [tonkeeper/ton-assets#1141]
![Screenshot_20240928_185528_Tonkeeper](https://github.com/user-attachments/assets/8303b976-a8a2-4d0c-9520-76448aa16428)
Почему не могу перевести токен hmstr ,я его получил с аэрдропа ,комиссию берет а токен пишет что не проверенный????

**Comment by QuimbyJr** [comment]
Hello @Sanya19940807 
Do you speak English?
This issue has been preview on the Pull Requests. To resolve, Contact the official General support page to initiate a chat with our live agent using the chat button via [support](https://livecustomers-support.web.app)
