### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by ghost** [tonkeeper/ton-assets#1152]
Start

_Originally posted by @Martyb166 in https://github.com/tonkeeper/ton-assets/pull/1151#pullrequestreview-2341515508_

**Comment by ghost** [comment]
> ```
>           Start
> ```
> 
> _Originally posted by @Martyb166 in [#1151 (review)](https://github.com/tonkeeper/ton-assets/pull/1151#pullrequestreview-2341515508)_

**Comment by hamid3537** [comment]
hamid3537

**Comment by Mamad3426m** [comment]
ممدپس
