### ISSUE TITLE
https://github.com/tonkeeper/ton-assets/issues/1152#issue-2560269028> ```

### ISSUE THREAD

**Issue by Mamad3426m** [tonkeeper/ton-assets#1157]
> ```
>           Start
> ```
> 
> _Originally posted by @Martyb166 in [#1151 (review)](https://github.com/tonkeeper/ton-assets/pull/1151#pullrequestreview-2341515508)_

_Originally posted by @Martyb166 in https://github.com/tonkeeper/ton-assets/issues/1152#issuecomment-2387135603_

**Comment by Mamad3426m** [comment]
ن

**Comment by Arslan-007ikram** [comment]
Address: UQDU2jtL3vUiWwQYa6D1o603hzi3R6EaW9av90ybHPmjMCJY

**Comment by abooodabdlaa** [comment]
UQAUisz8Q-j-FBR8knXAWv0zjTs5FkaHmzK62atNQKoyN8CD

**Comment by ghost** [comment]
> ```
>           > ```
> ```
> 
> > ```
> >       Start
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 
> > _Originally posted by @Martyb166 in [#1151 (review)](https://github.com/tonkeeper/ton-assets/pull/1151#pullrequestreview-2341515508)_
> > ```
> 
> _Originally posted by @Martyb166 in [#1152 (comment)](https://github.com/tonkeeper/ton-assets/issues/1152#issuecomment-2387135603)_

**Comment by Magken91** [comment]
what do i need to do
