### ISSUE TITLE
Didn't received the hamsters 

### ISSUE THREAD

**Issue by akam4258** [tonkeeper/ton-assets#1174]
In Tonkeeper transaction confirmed but I didn't get hamsters in my coinex account

**Comment by akam4258** [comment]
What I should do now?

**Comment by Krikor-tech** [comment]
Create chat with the support team regarding your transaction issue.

**Comment by akam4258** [comment]
Hi please guide me in this issue

**Comment by Krikor-tech** [comment]
![IMG_4884](https://github.com/user-attachments/assets/4bbcb2b5-86f4-47c5-acfe-f70952fceff8)
Kindly click on the live chat buttons to talk to the support team.

**Comment by Julietnacy** [comment]
@akam4258 It sounds like there might be a delay or an issue with the transaction. Have you checked the transaction ID on the blockchain to see if the transfer was successful?
