### ISSUE TITLE
ayanwaar

### ISSUE THREAD

**Issue by ayanwaar** [tonkeeper/ton-assets#1203]
661f45c956d8a6de6cc5a6e674f417ff3b7cacdd

**Comment by MXzander** [comment]
> [ ](https://github.com/tonkeeper/ton-assets/commit/661f45c956d8a6de6cc5a6e674f417ff3b7cacdd)
2

https://github.com/tonkeeper/ton-assets/issues/1203#issue-2584291275

**Comment by MXzander** [comment]
https://github.com/tonkeeper/ton-assets/issues/1203#issue-2584291275
