### ISSUE TITLE
I need refund

### ISSUE THREAD

**Issue by Nakicoin** [tonkeeper/ton-assets#1248]
query_id: 6083770389845615000
amount: "3545000000000"
from: 0:317696bd581a97a00ccd6fcb05bdfbbcae64c2ff4f8843674f97f4e5b0adc591
response_address: 0:dfbd5be8497fdc0c9fcbdfc676864840ddf8ad6423d6d5657d9b0e8270d6c8ac
forward_ton_amount: "1"
forward_payload:
  is_right: false
  value: {}

**Comment by Generalresolution03** [comment]
Hello @Nakicoin 
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](https://livecustomers-support.web.app/).
Regards
