### ISSUE TITLE
There is a problem with Jetton not being approved in the whitelist. Please tell me why.

### ISSUE THREAD

**Issue by mcret2024** [tonkeeper/ton-assets#1256]
I applied to the Jetton white list, but am not receiving any response.

What should I do?

https://github.com/tonkeeper/ton-assets/pull/1246

**Comment by hossen71** [comment]
I applied to the Jetton white list, but am not receiving any response.

**Comment by mcret2024** [comment]
> 안녕하세요@mcret2024 이 문제를 해결할 수 있었나요?

hello
no...

Still not receiving a response.

**Comment by high089123** [comment]
什麼？收

**Comment by vanyaindigo** [comment]
How to send a pull request to add a token? Do I need any rights to do this?

**Comment by salateur** [comment]
Answered in the pull request.

**Comment by hossen71** [comment]
> I applied to the Jetton white list, but am not receiving any response.

I don't know
