### ISSUE TITLE
me

### ISSUE THREAD

**Issue by ayanwaar** [tonkeeper/ton-assets#1308]
https://github.com/tonkeeper/ton-assets/blob/main/accounts.json#L4

**Comment by Hoangnam997** [comment]
UQAUxGo9p4B7ONERgx1uZevoyTY20SGzKMWHUDmVdHMHRQbz

**Comment by Hoangnam997** [comment]
UQAUxGo9p4B7ONERgx1uZevoyTY20SGzKMWHUDmVdHMHRQbz

**Comment by Hoangnam997** [comment]
UQAUxGo9p4B7ONERgx1uZevoyTY20SGzKMWHUDmVdHMHRQbz

**Comment by Hoangnam997** [comment]
nam11.oppo@gmail.com
