### ISSUE TITLE
Jetton Verify

### ISSUE THREAD

**Issue by LogicBolt** [tonkeeper/ton-assets#1328]
Hey Tonkeeper team!
happy to meet you guys. ^^
I contributed to Ton chain for nearly one year so now I want to verify one jetton
but there are too many failed Pull requests.
I want to know that reason.
What should I have to do for verify?
is there any special rule?
Thx

**Comment by saeedkalhor56** [comment]
متاسفانه من هم مشکل دارم

**Comment by Anvarkp** [comment]
> Hey Tonkeeper team!
> 
> happy to meet you guys. ^^
> 
> I contributed to Ton chain for nearly one year so now I want to verify one jetton
> 
> but there are too many failed Pull requests.
> 
> I want to know that reason.
> 
> What should I have to do for verify?
> 
> is there any special rule?
> 
> Thx
> 
>

**Comment by salateur** [comment]
Hello! Please read the following article: https://tonkeeper.helpscoutdocs.com/article/127-tokennftverification. If you find any other questions you can either create a new pull request and communicate there or write to the @help_tonkeeper_bot for further instructions.
