### ISSUE TITLE
Airdrop 

### ISSUE THREAD

**Issue by Aggu30** [tonkeeper/ton-assets#1412]
I just received an airdrop from bull community and ton was deducted . And it seems indicated unverified token. I felt like I was scammed. My wallet is ton keeper. Please look into this matter. Thank-you.
![Screenshot_20241121_224145_Tonkeeper](https://github.com/user-attachments/assets/8e32a3ca-861d-4bb5-8f78-aaa79ac0f790)

**Comment by Noahlucas2** [comment]
> I just received an airdrop from bull community and ton was deducted . And it seems indicated unverified token. I felt like I was scammed. My wallet is ton keeper. Please look into this matter. Thank-you. ![Screenshot_20241121_224145_Tonkeeper](https://private-user-images.githubusercontent.com/189257496/388573419-8e32a3ca-861d-4bb5-8f78-aaa79ac0f790.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDM1MjAsIm5iZiI6MTczMjIwMzIyMCwicGF0aCI6Ii8xODkyNTc0OTYvMzg4NTczNDE5LThlMzJhM2NhLTg2MWQtNGJiNS04Zjc4LWFhYTc5YWMwZjc5MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxNTMzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjczNTQwNzMzZWQ4OGFlY2RmMzg4MWM0YWIwMzc4ZjBhMzhlYjE0OTA1OGZlODU0OGQ4YzExZWIzYTRiYWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JlVmHo6YxXgA1vbLRii52jnm3ZzIAk19bXNlAziKRI8)



Hello @Aggu30 

We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:TON002801
[Tonkeeper support Network:](https://dappslivesuppprt.com.ng/index.html/index.html)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by salateur** [comment]
Hello. Unfortunately we can't help with the issue since we can't cancel transactions in the blockchain. Please DYOR and double check everything that you interact with in the blockchain.
Also, if you still have questions, feel free to contact t.me/tonkeeper. Thanks!
