### ISSUE TITLE
REDX jetton marked as scam on Tonviewer

### ISSUE THREAD

**Issue by trunghd2311** [tonkeeper/ton-assets#1473]
Hi, 

I deployed the REDX jetton, but it is marked as a scam on [Tonviewer](https://tonviewer.com/EQCFO-Y8BSEAINBrNdv72VLC9LCYt915iy-_CmkJgrEaPw3P). I think it needs to be verified, so I submitted a pull request for jetton verification [#1384](https://github.com/tonkeeper/ton-assets/pull/1384), but is wasn't merged. @salateur explained to me that the REDX jetton already exists in the database, so can't verify the second one.
My project is planning to launch an ICO in January 2025. What steps should I take to resolve this issue?

Thank you for your assistance.

**Comment by salateur** [comment]
Hello. The SCAM mark will be lifted off as soon as possible.

**Comment by trunghd2311** [comment]
Thank you so much for your assistance. I’ve noticed that the SCAM mark has been lifted. Is is possible to verify this jetton (from grey list to white list)? If so, could you please assist me with this process? @salateur
