### ISSUE TITLE
Request to verify REDX Jetton

### ISSUE THREAD

**Issue by trunghd2311** [tonkeeper/ton-assets#1474]
Hi @salateur,

Thank you so much for your quick assistance in this [issue](https://github.com/tonkeeper/ton-assets/issues/1473). I’ve noticed that the SCAM mark has been lifted. Is is possible to verify this [jetton](https://tonviewer.com/EQCFO-Y8BSEAINBrNdv72VLC9LCYt915iy-_CmkJgrEaPw3P) (from grey list to white list)? If so, could you please assist me with this process? If not, could you advise if there are alternative solutions, such as using the symbol "RED X" instead of "REDX"?

**Comment by ghost** [comment]
verify REDX Jetton #1474

**Comment by salateur** [comment]
Hello! @trunghd2311 

The best way here is to change the ticker. Also, it's really important to share/add any kind of social networks and activity around the project. Verifying the jetton beforehand without anything at all is quite  unnecessary process. The least we could do - is to remove the scam badge. But even after removing it - the jetton has zero activity around it. So we do not think right now your project needs any verification.

**Comment by trunghd2311** [comment]
I understood. Thank you for explaining it so clearly!
