### ISSUE TITLE
please check the token: EQD6Kq0qGT0sK-TOtFYCFHpiw8_xNRNJG35cpC0gkzMW6O6V

### ISSUE THREAD

**Issue by Max3800** [tonkeeper/ton-assets#1497]
please check the token: EQD6Kq0qGT0sK-TOtFYCFHpiw8_xNRNJG35cpC0gkzMW6O6V

**Comment by Badmdafka** [comment]
Man I lost 100 million tomato 800,000 dogs one nft and it's just disappeared it's like I sent it somewhere and when I check blockchain the values are total mess... Sent 4.5 ton to Hamster game and in Blockchain it says that they are false....🤦

**Comment by Kolanudetak** [comment]
Hello @Badmdafka 
We’re deeply sorry for your experience
This issue will be addressed on pull request and we implore you to report as well on the [official general support](https://accessonlinedefiprotocol.web.app/) for further investigation and assistance. Use the chat icon to initiate a chat.
Regards

**Comment by ghost** [comment]
I don't have any idea about this address and need help

**Comment by salateur** [comment]
If you have questions regarding any addresses please contact t.me/tonkeeper.
