### ISSUE TITLE
Request for verification MMM coin

### ISSUE THREAD

**Issue by dumitru1994stati** [tonkeeper/ton-assets#1546]
name: Dmitry Stati 
description: MMM coin was inspired by Serghey Mavrodi and his stock company wich was a financial pyramid in 1990's we create it for people who now understand what is the world crypto and meme coins, to inspire them an make them buy!!! :D 
address:EQCgj0OpHgmojJvQukVbsICAAChH0qrWcYryyvQHz3HdaLaU

symbol: MMM

social:
  https://t.me/MMM_cryptocurrency

Hope you understand us)

**Comment by ayanwaar** [comment]
015d29c9760fcb10399ae268d3372badb38d07d1

**Comment by salateur** [comment]
Tonkeeper reserves the right to refuse verification without any explanation
