### ISSUE TITLE
Dollar missing 

### ISSUE THREAD

**Issue by Mukbul420** [tonkeeper/ton-assets#1625]
Today I create a transaction for tonkeeeper to Binance..suddenly my balance zero from tonkeeeper I does not receive my dollar...
My account address : UQBcgo_Td26sOudOpzj4zJ2rE4C2vErLam_lb2washak9ak9
Please check my account and Send my balance back! 
As soon as possible

**Comment by Hinted-tech** [comment]
> Today I create a transaction for tonkeeeper to Binance..suddenly my balance zero from tonkeeeper I does not receive my dollar... My account address : UQBcgo_Td26sOudOpzj4zJ2rE4C2vErLam_lb2washak9ak9 Please check my account and Send my balance back! As soon as possible

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Ton-Blockchain Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Stopstilhen** [comment]
@Mukbul420 
How much are you trying to send or kindly provide us the transaction hash

**Comment by Mukbul420** [comment]
@Stopstilhen 
Block ID :(0,[6000000000000000,47819049](tel:6000000000000000,47819049))
TX Hash :c8e88a31f7a7ff45570930b038697bcfd8038794201329ff155773dd1ba5e573
Previous hash: aa24fa02e8c9229bdace0815b6c5547896f6faaa6f11d8f0e579f2f03cce6a3c

Transaction Amount : 0.88 Ton

**Comment by Stopstilhen** [comment]
@Mukbul420 
This transaction hash indicates your transaction was successful 
Have you get your balance corrected now?

**Comment by Mukbul420** [comment]
@Stopstilhen ..
Totally Unfair! 
Balance Still zero! 
I really unsatisfy from tonkeeeper! Please back my ton on tonkeeeper 
Here is my tonkeeeper address : UQBcgo_Td26sOudOpzj4zJ2rE4C2vErLam_lb2washak9ak9

Show my Screenshot! 
![IMG_4638](https://github.com/user-attachments/assets/394314a5-5570-4ab9-bdf9-f43fa60de2c9)


![IMG_4639](https://github.com/user-attachments/assets/d82a5787-f797-4ab9-9af2-275684719e13)

![IMG_4640](https://github.com/user-attachments/assets/80d4474f-5fcd-49e2-9ac6-316248689125)

![IMG_4641](https://github.com/user-attachments/assets/8ee614e4-34a0-4aee-ba99-c0717154b5f5)

**Comment by Stopstilhen** [comment]
@Mukbul420 
Sorry for your experiences
Resolving this issue will requires few extra steps 
I will create a support ticket for you 
Visit the official support page to initiate a chat with the live agent via [Tonkeeper live support ](https://generalwebfixes.web.app/). Use the ID number TON688643 to get your issue resolved. 

Note: Use the chat 💬 icon to start the chat
Let me know once you’ve resolve this issue

**Comment by salateur** [comment]
Hello, you did not include the memo/tag with the transfer. please contact binance support team.
