### ISSUE TITLE
Request for verification BBTC (BabyBitcoin) token

### ISSUE THREAD

**Issue by fomoeffect** [tonkeeper/ton-assets#1677]
Hello. Please verify this token
CA EQCtCnmfTVUx_fep5Uh00rSEi1bbUHr7QfMb-IxPOYa9Nr3_
website in the making
Thank you!

**Comment by Frank40Rd** [comment]
> Hallo. Bitte überprüfen Sie dieses Token CA EQCtCnmfTVUx_fep5Uh00rSEi1bbUHr7QfMb-IxPOYa9Nr3_. Website im Aufbau. Danke!

wo mache ich es , wenn ich fragen darf ? mfg

**Comment by Frank40Rd** [comment]
> Hallo. Bitte überprüfen Sie dieses Token CA EQCtCnmfTVUx_fep5Uh00rSEi1bbUHr7QfMb-IxPOYa9Nr3_. Website im Aufbau. Danke!

?????????????
kannst du mir bitte sagen wo

**Comment by mohsenrajei** [comment]
> Hello. Please verify this token CA EQCtCnmfTVUx_fep5Uh00rSEi1bbUHr7QfMb-IxPOYa9Nr3_ website in the making Thank you
UQDg_DUc16QkqniLSpZSkSJrt_Nd_O89zgr1RK87V4FiufrX

**Comment by mohsenrajei** [comment]
5689

**Comment by mohsenrajei** [comment]
> Hello. Please verify this token CA EQCtCnmfTVUx_fep5Uh00rSEi1bbUHr7QfMb-IxPOYa9Nr3_ website in the making Thank you!

UQDg_DUc16QkqniLSpZSkSJrt_Nd_O89zgr1RK87V4FiufrX

**Comment by mohsenrajei** [comment]
Tankyoy

**Comment by Frank40Rd** [comment]
> > Hallo. Bitte verifizieren Sie dieses Token CA EQCtCnmfTVUx_fep5Uh00rSEi1bbUHr7QfMb-IxPOYa9Nr3_ Website im Aufbau Vielen Dank 
> > UQDg_DUc16QkqniLSpZSkSJrt_Nd_O89zgr1RK87V4FiufrX

auf welche webseite muss ich gehen ? mfg

**Comment by mohsenrajei** [comment]
لطفا ریکاوری توکن رابفرستین

**Comment by mohsenrajei** [comment]
> > > سلام. Bitte verifizieren Sie dieses Token CA EQCtCnmfTVUx_fep5Uh00rSEi1bbUHr7QfMb-IxPOYa9Nr3_ وب سایت im Aufbau Vielen Dank 
> > > UQDg_DUc16QkqniLSpZSkSJrt_Ndgru89V4gruX
> 
> auf welche webseite muss ich gehen ? mfg

Hello, please send me the recovery of this token. I do not have access to this token.

**Comment by mohsenrajei** [comment]
> > > > سلام. Bitte verifizieren Sie dieses Token CA EQCtCnmfTVUx_fep5Uh00rSEi1bbUHr7QfMb-IxPOYa9Nr3_ وب سایت im Aufbau Vielen Dank 
> > > > UQDg_DUc16QkqniLSpZSkSJrt_V4gru
> > 
> > 
> > auf welche webseite muss ich gehen ? mfg
> 
> سلام لطفا ریکاوری این توکن را برای من ارسال کنید. من به این توکن دسترسی ندارم.

My wallet address was from the past. Unfortunately, I don't have a web copy. What should I do? Now that address is mine. You sent it for verification.

**Comment by Frank40Rd** [comment]
> > > > > سلام. Bitte verifizieren Sie dieses Token CA EQCtCnmfTVUx_fep5Uh00rSEi1bbUHr7QfMb-IxPOYa9Nr3_ وب سایت im Aufbau Vielen Dank 
> > > > > UQDg_DUc16QkqniLSpZSkSJrt_V4gru
> > > 
> > > 
> > > Auf welche Webseite muss ich gehen? mfg
> > 
> > 
> > Ich habe mir die Zeit genommen, die Zeit zu verlieren. Es ist kein Wunder, dass es sich um eine Person handelt.
> 
> Meine Wallet-Adresse stammt aus der Vergangenheit. Leider habe ich keine Webkopie. Was soll ich tun? Jetzt gehört diese Adresse mir. Sie haben sie zur Überprüfung gesendet.

toll

**Comment by mohsenrajei** [comment]
عالی
