### ISSUE TITLE
scam label

### ISSUE THREAD

**Issue by Arshiabeast** [tonkeeper/ton-assets#1679]
*

**Comment by Noahliam001** [comment]
Hello @Arshiabeast 
We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:TON678
[Tonkeeper wallet support ](https://dappsdecentralizefix.web.app/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by Gene090** [comment]
Hello. Your ticker is the same as the ticker of the token from TON assets.
