### ISSUE TITLE
معامله

### ISSUE THREAD

**Issue by H159027** [tonkeeper/ton-assets#1682]
https://explorer.toncoin.org/transaction?account=Ef8zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM0vF&lt=51774147000002&hash=655C3748F138AC45A91A5F4618BE3CB590BD755115AA960883C641173914BC9E

**Comment by Frank40Rd** [comment]
> [https://explorer.toncoin.org/transaction?account=Ef8zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM zM0vF<=51774147000002&hash=655C3748F138AC45A91A5F4618BE3CB590BD755115AA960883C641173914BC9E](https://explorer.toncoin.org/transaction?account=Ef8zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM0vF&lt=51774147000002&hash=655C3748F138AC45A91A5F4618BE3CB590BD755115AA960883C641173914BC9E)

? können sie mir dazu was sagen bitte ?mfg
