### ISSUE TITLE
Unverified token-Dogs 

### ISSUE THREAD

**Issue by chitara19** [tonkeeper/ton-assets#1713]
Token- Dogs 
Address- EQBpBnZUW3X8qHAS1eJLSKeqFHa7PvIvkxhYu0SxE4xQtftn
Can you verify my dogs tokens that were claimed for tasks completed,  shows unverified. 
Wallet address- UQDXcydFveC13aE1Buw7-iUBl1dMkuItRaMQAxDBTZwgppMp
Total amount unverified is 87438 dogs from airdrop
![Screenshot_20241213_011509_Binance](https://github.com/user-attachments/assets/200b7b59-7b21-4ebb-8d15-d6227d899bb2)

**Comment by Drianna75** [comment]
Hi @chitara19 

A complaint has be lodged and ticket has been established for your issue (Ticket number #TON66362)
Visit the official support website to initiate a chat with the support team via [TON Live chat](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generated for you to properly rectify the problem.

**Comment by salateur** [comment]
Hello, please contact the tokens issuer instead.
