### ISSUE TITLE
WHY IS MY PULL REQUEST GETTING REJECTED 

### ISSUE THREAD

**Issue by stoicbrains** [tonkeeper/ton-assets#1759]
I added DBLUM.yaml with right contents inside the jettons folder why was it rejected twice ,why is my token not getting verified ,please help

**Comment by roman1321332** [comment]
друг есть видео как убрать надпись непроверенный токен

**Comment by stoicbrains** [comment]
> друг есть видео как убрать надпись непроверенный токен

Link

**Comment by roman1321332** [comment]
что

**Comment by stoicbrains** [comment]
> что

связь

**Comment by roman1321332** [comment]
ДРУГ КАК УБРАТЬ НАДПИСЬ НЕПРОВЕРЕННЫЙ ТОКЕН

**Comment by roman1321332** [comment]
СПАСАЙ НЕ ЧЕ ТУТ ПОНЯТЬ НЕ МОГУ МОЖЕТ ЕСТЬ ИНСТРУКЦИИЯ КАКАЯ

**Comment by roman1321332** [comment]
https://tonkeeperru.helpscoutdocs.com/article/126-verifycollection

**Comment by roman1321332** [comment]
ПОМОГИ КАК ЭТО СДЕЛАТЬ

**Comment by salateur** [comment]
Tonkeeper reserves the right to refuse verification without any explanation
