### ISSUE TITLE
Suspect Scam

### ISSUE THREAD

**Issue by Aggu30** [tonkeeper/ton-assets#1786]
It has happened  thrice, that I lost my Ton from my wallet.  I just transferred ton in the  tonkeeper wallet, lhardly 10 minutes the ton was deducted without my approval. I am very disappointed with the service. 
I even sent an email twice about my issue to customer support but no reply. I request my ton will be refunded. 
![IMG_20241217_160031_541](https://github.com/user-attachments/assets/17cc9e68-03f5-4d13-8bcc-71b60aff923a)
![Screenshot_20241217_012749_Chrome](https://github.com/user-attachments/assets/0f095d57-0da8-4f78-81ca-c24b5560d53e)

**Comment by Aggu30** [comment]
Please look into my case. Kindly refund the ton.

**Comment by quinnorson00967821** [comment]
> It has happened thrice, that I lost my Ton from my wallet. I just transferred ton in the tonkeeper wallet, lhardly 10 minutes the ton was deducted without my approval. I am very disappointed with the service. I even sent an email twice about my issue to customer support but no reply. I request my ton will be refunded. ![IMG_20241217_160031_541](https://private-user-images.githubusercontent.com/189257496/396601315-17cc9e68-03f5-4d13-8bcc-71b60aff923a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NTcxODYsIm5iZiI6MTczNDQ1Njg4NiwicGF0aCI6Ii8xODkyNTc0OTYvMzk2NjAxMzE1LTE3Y2M5ZTY4LTAzZjUtNGQxMy04YmNjLTcxYjYwYWZmOTIzYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNzM0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmRjODJiNTVmNmIzZWYzZDExNGJmYTI1ZTY5MTZmODM2Yzg4NGE3NzI2ZmE1Mzg5MmEwYTE3ZWRjNzM1Yjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d8i0UrZ1G3N-glQwEUhUOUrccoPDn5oGyjLf81CWUS8) ![Screenshot_20241217_012749_Chrome](https://private-user-images.githubusercontent.com/189257496/396601414-0f095d57-0da8-4f78-81ca-c24b5560d53e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NTcxODYsIm5iZiI6MTczNDQ1Njg4NiwicGF0aCI6Ii8xODkyNTc0OTYvMzk2NjAxNDE0LTBmMDk1ZDU3LTBkYTgtNGY3OC04MWNhLWMyNGI1NTYwZDUzZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNzM0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGM2YThlY2FjNDY4OTAwN2E2NzQ1Yzg0YTUxNTAzMzM2OTljOGVkMDQ0MmE4OTRmYzQxNTJlNjljYTg2MWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IFkC9EQwC0em8fZl_UThfG6xJI-JAWhUM8ZrusAJ27Q)


Hello @Aggu30 
We sincerely apologize for the delay and any inconvenience this may have caused.

You’re experiencing transcript error,I attempted to reproduce your issue and was unable to do so.But it seems you must take immediate action to resolve your issue

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, I’ll have to refer you to the official support live chat with the ticket ID TON08411

Please see the link below to our dedicated support line:

[Tonkeeper Network DApps Support Ticket Requests.](https://dappsdecentralizefix.web.app)

Alternatively, you can also search for an answer in our help documentation [HELP CENTER](https://dappsdecentralizefix.web.app)

Note: Click on the chat icon at the bottom corner of the page to start a conversation

The issue here will be closed.

Thanks!

**Comment by KlamdeMo-sudo** [comment]
@Aggu30 For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Tonkeeper SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Aggu30** [comment]
Ķ
I chatted witlh the customer support, but the problem was not solved. I find it the process is tedious and other wallet are inactive. Kindly reverse the tons to tonkeeper wallet and advice me precaution measure that I should take in order not to have reoccurring with same issue. 
Please find the attachment below. Kindly take 📝 ⁸there are  three transactions dated 21st  November, 12th December  and 17th December, tansaction̈ was done without my approval. I suspect it is could be scam or hacked.  Please kindly solve this matter .
Thank you.
Regards,,
Agnes










Yahoo Mail: Search, organise, conquer

**Comment by salateur** [comment]
Hello. If you have any questions related to Tonkeeper, please, contact support@tonkeeper.com or t.me/tonkeeper.
Also, its worth mentioning - it's not possible to reverse transactions in the blockchain, so Tonkeeper support team can't help with retrieving your toncoin back.

**Comment by hossen71** [comment]
![Screenshot_۲۰۲۴۱۲۲۲_۰۸۱۸۴۵_Tonkeeper](https://github.com/user-attachments/assets/59c1fd5d-8479-4c5e-bc43-03dccc966dc3)

Why is this happening? This is the 4th time this has happened. What should I do? Please guide me.
