### ISSUE TITLE
Please change Token Address.

### ISSUE THREAD

**Issue by AlexSimakhin** [tonkeeper/ton-assets#1835]
@kot04 Please change Token Address.
@Gene090 @xximwon Please check the addresses carefully.

_Originally posted by @AlexSimakhin in https://github.com/tonkeeper/ton-assets/issues/1822#issuecomment-2558211576_

Wrong Token Address

**Comment by AlexSimakhin** [comment]
https://github.com/tonkeeper/ton-assets/pull/1822

**Comment by AlexSimakhin** [comment]
Please approve #1847
Because PR #1822 changed the metadata for MEZO

**Comment by kot04** [comment]
> Please approve #1847 Because PR #1822 changed the metadata for MEZO
I'm sorry again that it happened this way, I didn't mean to
