### ISSUE TITLE
Verification of Token $ Duplo

### ISSUE THREAD

**Issue by ShaftBros** [tonkeeper/ton-assets#1871]
I would like to request the verification of our toke DUPLO, on your platform. Below are the details of the token:

{
  "address": "0:eb25e13aada725b092badab3ca031dde3fb4c4f113013a740bb6797d4fb233fc",
  "name": "Duplo YupLand ",
  "symbol": "Duplo",
  "decimals": "9",
  "https://cache.tonapi.io/imgproxy/R3AszpYKrakVLxsPsyo5wwQ-Wllmd7kSKt22kPTJfUQ/rs:fill:200:200:1/g:no/aHR0cHM6Ly9pcGZzLmhvdGRhby5haS9pcGZzL2JjaXFocXptMml6aDZ0bzUyc21zaHpsazN0NGVldW43bTN5dXJhYWNxbzNtaXd1bHhsdDI0bmdh.webp",
  "description": "Own the hollow"

social: https://t.me/yupland

**Comment by salateur** [comment]
Please create a pull request instead so we could check it.
