### ISSUE TITLE
Verify TONs 

### ISSUE THREAD

**Issue by Maherrashed50** [tonkeeper/ton-assets#1877]
UQDy5TiO2dEyc-uGoZO9dpd2PtD29PYnp-y4qz9ZRgAX1ORk

I dont know wgy are like that 
![IMG_9939](https://github.com/user-attachments/assets/7fe3db15-ea7e-47df-8ddb-9a8528f910b7)

i lost 2.5 TON and I revice 26 TONS

**Comment by salateur** [comment]
Hello! Please contact t.me/tonkeeper. Also, it seems you've received a scam token.
