### ISSUE TITLE
unverified token

### ISSUE THREAD

**Issue by Maherrashed50** [tonkeeper/ton-assets#1878]
would like to request the verification of our toke
TONS, on your platform. Below are the details of the token:

aderss:  UQA7J702rBJ49BnGSJYESOe1x6wnwya72d_68zXcyNnXQwUe
Name: “TONS“
Symbol: “TONS“
Adress :  UQA7J702rBJ49BnGSJYESOe1x6wnwya72d_68zXcyNnXQwUe
![IMG_9939](https://github.com/user-attachments/assets/ecd3e24c-75f8-4016-97ea-94bb2023cf32)

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by salateur** [comment]
No comment here :)
