### ISSUE TITLE
Unverified tokens

### ISSUE THREAD

**Issue by chitara19** [tonkeeper/ton-assets#1924]
![Screenshot_20241213_011509_Binance](https://user-images.githubusercontent.com/26846512/399310974-3f8bedcf-b7eb-4669-a2cf-f216d25dd4d1.jpg)
              Hello, please contact the tokens issuer instead.

_Originally posted by @salateur in https://github.com/tonkeeper/ton-assets/issues/1713#issuecomment-2545370939_

**Comment by Fonseca624** [comment]
Hello @chitara19  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
