### ISSUE TITLE
Прошу проверить мой жетон: Uni/TON

### ISSUE THREAD

**Issue by Dimaosadchuk888** [tonkeeper/ton-assets#556]
Адрес: 

Jetton master 

EQCH4I_01vxJtoTRQ8hfy7cr81ZmsiiEi2iMn_Yjgv3aLQjE

Jetton wallet 

EQCTLcCMlCiN-cuhnZ_Uznd4iZdYoFfDlDiCGZ8GtGt9RCJC

**Comment by 18211308** [comment]
@aleksej-paschenko
