### ISSUE TITLE
Fake $LADY token copy 

### ISSUE THREAD

**Issue by Linuxuser999** [tonkeeper/ton-assets#680]
I am a holder of the first launched $LADY burned lp and revoked and a copy cat project popped up 4 hours after. It's causing a lot of confusion between people and it's hurting the original Lady! Very malicious activity. 

First Pair created 13 hours ago 

Contract: EQASaIVDyf8QBfhiLUOeiu2ayVoPZYadaPQTUAO1uED6TvAA

![image](https://github.com/tonkeeper/ton-assets/assets/145880895/a941f614-303d-47b8-bec5-507808a85e24)

Second Pair created (copy cat) created 7 hours ago

Fake Contract: EQBowEMCNat-oFMWbRhhGBaEVxQO5qhyqei4P74D2xhx-TR6

![image](https://github.com/tonkeeper/ton-assets/assets/145880895/10205320-5ef3-493f-9dd6-bcf306c6fca6)

**Comment by Themushroommafia** [comment]
I'm also a holder of the original burnt/revoked LADY (CA: EQASaIVDyf8QBfhiLUOeiu2ayVoPZYadaPQTUAO1uED6TvAA, and it's causing all of our holders additional stress to have this copycat out there, I would love to see the issue resolved

**Comment by Linuxuser999** [comment]
![image](https://github.com/tonkeeper/ton-assets/assets/145880895/f5fa1eaa-787f-446e-8d64-a1529a4b03e1)

As you can see above is the portal for the fake coin they copied the exact pinned twitter message from the real group below (difference in time: 8 hour difference)

![image](https://github.com/tonkeeper/ton-assets/assets/145880895/6021a31e-c305-4fbc-b8df-71e9509b8d5b)

The only thing changed was to a different twitter. Lack of effort showing malicious intent. Why create the exact same coin already out. This dev is clearly trying to make money off people getting confused.  

I think tokens like this need some sort of warning to protect investors

**Comment by Linuxuser999** [comment]
More evidence of bad intention

Fake project created a pull request for their token to be updated. After commenting about it the post was deleted. This is clearly a dev trying to hide the facts it is a copy. 

![image](https://github.com/tonkeeper/ton-assets/assets/145880895/8c6a4fc1-af1e-410d-8565-735c384ca6f4)

![image](https://github.com/tonkeeper/ton-assets/assets/145880895/8d05c00e-4fdc-4efb-9d23-edf1bfa0f488)

**Comment by Linuxuser999** [comment]
before 
![image](https://github.com/tonkeeper/ton-assets/assets/145880895/19e028c4-6b6b-4522-a88a-5489bf664300) 

After
![image](https://github.com/tonkeeper/ton-assets/assets/145880895/ff59ee48-1a06-4ef0-a039-34f3830ea751)

More evidence of hiding tracks / covering up that they were copying our token group. Obviously the devs behind this scam are watching this and changing everything they can to save themselves.

**Comment by Themushroommafia** [comment]
What the fuck. Y'all never even attempted to fix the issue
