### ISSUE TITLE
Mislabel on the Original $LADY 

### ISSUE THREAD

**Issue by TonHelper1** [tonkeeper/ton-assets#734]
I am writing to bring to your attention a significant issue affecting our project, $LADY, which can be found here: https://tonviewer.com/EQASaIVDyf8QBfhiLUOeiu2ayVoPZYadaPQTUAO1uED6TvAA?section=jetton. Recently, our project was mistakenly labeled as a scam, while another project that copied our meme coin and launched 8 hours later was verified by Tonkeeper and Tonviewer. You can view the verified project here: https://tonviewer.com/EQBowEMCNat-oFMWbRhhGBaEVxQO5qhyqei4P74D2xhx-TR6?section=jetton.

This wrongful mislabeling has severely impacted our investors and the price of our token. As the original $LADY, we know that the scam label was incorrectly applied to our token. From the beginning, our community has raised concerns about the copycat project that stole our media. We even filed a GitHub issue on the Tonkeeper repository, highlighting the malicious intent of the other project that copied: https://github.com/tonkeeper/ton-assets/issues/680.

Our project's key transactions that prove we were the original $Lady and later copied are as follows:

Deployment: 13.06.2024, 23:02:27 - https://tonviewer.com/transaction/1e5303b794dd62e207d0ee3748f50855a747f622b989c94742649f0bcd7d32cc
Pool creation and liquidity addition: 13.06.2024, 23:02:27 - https://tonviewer.com/transaction/2019ef0aef2b1968f4d19a2e667468be4a1ba4e729cea6ac187ed496bc0c4449
Liquidity burn transactions: 13.06.2024, 23:49:25 - https://tonviewer.com/transaction/1ca1985c0818f8a001736eae5d7e0473f4353ed43592007f11e3033b5d6fb606 and 13.06.2024, 23:53:56 - https://tonviewer.com/transaction/8f331779aafddc463c49dbfe5aed399939909ceedfa8ee3916d0fcdf3c832e82
Approximately 8 hours after our token was thriving, another project deployed a second $LADY token. This project copied our pinned post. A community member reported this on GitHub, showing how the fake project copied our pinned message and then changed everything to cover their tracks once it was posted: https://github.com/tonkeeper/ton-assets/issues/680.

Our project submitted a token request before the fake project:

Our request: https://github.com/tonkeeper/ton-assets/pull/679
Fake project request: https://github.com/tonkeeper/ton-assets/pull/683
The key transactions for the copycat project are:

Deployment: 14.06.2024, 05:14:45 - https://tonviewer.com/transaction/cd4297e64b9e4898e9db4ff863082ba229fb63babf28019787ba555197ee8455
Liquidity addition: 14.06.2024, 05:22:20 - https://tonviewer.com/transaction/5452103193416c81879c81aba37e374b0ce8a1f888db198a7c65243791d597eb
This project maliciously copied ours 8 hours later. The scam label was wrongly applied to our project, causing significant harm.

We urge @TONBlockchain, tonkeeper, and tonviewer to address this issue and correct the scam label on our original $LADY token. This is a significant injustice on a blockchain that is supposed to be decentralized.

Thank you for your time and consideration. We hope you can rectify this situation to support our community and ensure the integrity of the TON ecosystem.

Best regards,
Darth Duck
Deployer of the original $LADY
![copycat portal](https://github.com/tonkeeper/ton-assets/assets/172461994/ef5b9fa9-056b-4382-b85b-e837db398729)
![age](https://github.com/tonkeeper/ton-assets/assets/172461994/091f67f6-8b3c-4085-8d99-607cb5af2913)

**Comment by Hamlo98** [comment]
> Я пишу, чтобы обратить ваше внимание на важную проблему, затрагивающую наш проект $LADY, которую можно найти здесь: https://tonviewer.com/EQASaIVDyf8QBfhiLUOeiu2ayVoPZYadaPQTUAO1uED6TvAA?section=jetton . Недавно наш проект был ошибочно назван скамом, а другой проект, скопировавший нашу мем-монету и запущенный 8 часов спустя, был проверен Tonkeeper и Tonviewer. Вы можете просмотреть проверенный проект здесь: https://tonviewer.com/EQBowEMCNat-oFMWbRhhGBaEVxQO5qhyqei4P74D2xhx-TR6?section=jetton .
> 
> Эта неправомерная маркировка серьезно повлияла на наших инвесторов и цену нашего токена. Как исходный $LADY, мы знаем, что к нашему токену был неправильно применен ярлык мошенничества. С самого начала наше сообщество выразило обеспокоенность по поводу проекта-подражателя, который украл наши средства массовой информации. Мы даже зарегистрировали проблему на GitHub в репозитории Tonkeeper, подчеркнув злонамеренные намерения другого скопировавшего проекта: #680 .
> 
> Ключевые транзакции нашего проекта, которые доказывают, что мы были оригинальной $Lady, а затем скопированы, заключаются в следующем:
> 
> Развертывание: 13.06.2024, 23:02:27 - https://tonviewer.com/transaction/1e5303b794dd62e207d0ee3748f50855a747f622b989c94742649f0bcd7d32cc Создание пула и пополнение ликвидности: 13.06.2024, 23:0 2:27 – https://tonviewer.com/transaction/2019ef0aef2b1968f4d19a2e667468be4a1ba4e729cea6ac187ed496bc0c4449 Транзакции сжигания ликвидности: 13.06.2024, 23:49:25 - https://tonviewer.com/transaction/1ca1985c0818f8a001736eae5d7e0473f4353ed43592007f11e3033b5d6fb606 и 13.06.2024, 23:53:56 - [https ://tonviewer.com/transaction/8f331779aafddc463c49dbfe5aed399939909ceedfa8ee3916d0fcdf3c832e82](https://tonviewer.com/transaction/8f331779aafddc463c49dbfe5aed399939909ceedfa8ee3916d0fcdf3c832e82) Примерно 8 часов после того, как наш токен стал процветать, другой проект внедрил второй токен $LADY. Этот проект скопировал наш закрепленный пост. Член сообщества сообщил об этом на GitHub, показав, как фейковый проект скопировал наше закрепленное сообщение, а затем изменил все, чтобы замести следы после его публикации: #680 .
> 
> Наш проект отправил запрос токена до фейкового проекта:
> 
> Наш запрос: [№679](https://github.com/tonkeeper/ton-assets/pull/679) Запрос поддельного проекта: [№683](https://github.com/tonkeeper/ton-assets/pull/683) Ключевые транзакции проекта-подражателя:
> 
> Развертывание: 14.06.2024, 05:14:45 - https://tonviewer.com/transaction/cd4297e64b9e4898e9db4ff863082ba229fb63babf28019787ba555197ee8455 Добавление ликвидности: 14.06.2024, 05:22:20 - https://tonviewer.com/transaction/5452103193416c81879c81aba37e374b0ce8a1f888db198a7c65243791d597eb Этот проект злонамеренно скопировал наш 8 часов спустя. Ярлык мошенничества был ошибочно применен к нашему проекту, что нанесло значительный вред.
> 
> Мы призываем@tonblockchain, tonkeeper и tonviewer, чтобы решить эту проблему и исправить метку мошенничества на нашем исходном токене $LADY. Это серьезная несправедливость по отношению к блокчейну, который должен быть децентрализованным.
> 
> Спасибо за ваше время и внимание. Мы надеемся, что вы сможете исправить эту ситуацию, чтобы поддержать наше сообщество и обеспечить целостность экосистемы TON.
> 
> С уважением, Дарт Дак, разработчик оригинальной $LADY. ![портал-подражатель](https://private-user-images.githubusercontent.com/172461994/342127683-ef5b9fa9-056b-4382-b85b-e837db398729.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODMwMjYsIm5iZiI6MTcxOTI4MjcyNiwicGF0aCI6Ii8xNzI0NjE5OTQvMzQyMTI3NjgzLWVmNWI5ZmE5LTA1NmItNDM4Mi1iODViLWU4MzdkYjM5ODcyOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwMjMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjBlNTQ2OWY3YWRjNmIzNjI4OTJmMjRmNGNjOWE0YWRiMTQ5ZTZhNTgxZWYzYWZkZGMxMTBjYTY4OTk1MmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IuHDfeiQrgBX_WwO_oh9SdgYUXHsUIL6Bc1m_rPv5vc) ![возраст](https://private-user-images.githubusercontent.com/172461994/342127690-091f67f6-8b3c-4085-8d99-607cb5af2913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODMwMjYsIm5iZiI6MTcxOTI4MjcyNiwicGF0aCI6Ii8xNzI0NjE5OTQvMzQyMTI3NjkwLTA5MWY2N2Y2LThiM2MtNDA4NS04ZDk5LTYwN2NiNWFmMjkxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwMjMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWIzNDJjMTM3ZmQ4N2EwY2Q1NWExZGQ1MjBiZmNmYTM4NmE4YzUyNDAyNmFhY2FhODA0MThlOTIyNDY5NDY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nw_FmYAXPUHoxoI-VTlknRpbdtoHdslf7UhjQR2tgsA)
