### ISSUE TITLE
Mislabel of $PEPE (Ton Pepe)

### ISSUE THREAD

**Issue by berpetuals** [tonkeeper/ton-assets#771]
I am writing to bring to your attention a significant issue affecting our project, $PEPE which can be found here: https://tonviewer.com/EQDPdNEYKpn26W-fgNVt6nyMgt3FFeEQmQwtcAFGxnhs1pUh. Our project was mistakenly labeled as a scam, despite our token being the first original "TON PEPE" on TON. 

This wrongful mislabeling has severely impacted our investors, fans and the price of our token. As the original "Ton Pepe" $PEPE, we believe that the scam label was incorrectly applied to our token. Our community has raised concerns about the scam label as our token celebrates the original green pepe meme. 

We humbly request that @tonblockchain, Tonview, and Tonkeeper to address this issue and correct the scam label on our original "Ton Pepe" $PEPE token. We are a hard working team that is pushing out content daily, want the token to succeed for PEPE fans, and believe this treatment is unfair to both existing and prospective investors. 

Thank you for your time and consideration. We hope that this issue can be resolved for everyone, and the integrity of the TON ecosystem.

Kind regards,
Brypto
Deployer of $PEPE

**Comment by Sweetmind300** [comment]
Hi @berpetuals, are you the Dev in charge of? 
kindly visit the official general support page to resolve this issue or report for further assistance via [Support](https://accessonlinedefiprotocol.web.app/)

Note: you can also initiate a chat with the support team using the chat icon on the page.
