### ISSUE TITLE
FLIKI Token Contract EQAubtiqhtxuBib4Rr5DxBXHKq80mnYdJ8VdfjhpY2FU7Z65

### ISSUE THREAD

**Issue by bradsy2** [tonkeeper/ton-assets#801]
Please add my token so that it is not an untested token.

**Comment by Demistumod67** [comment]
@Freddie194 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
