### ISSUE TITLE
Добавьте монету LIONFI

### ISSUE THREAD

**Issue by AsianMokaev** [tonkeeper/ton-assets#825]
Пожалуйста добавьте жетон LIONFI. 

EQCOzPXWWFA1VFR8jKPNij-TlA78yMZa8TP_VcMc5joZkqE9

**Comment by AsianMokaev** [comment]
{
  "address": "0:8eccf5d658503554547c8ca3cd8a3f93940efcc8c65af133ff55c31ce63a1992",
  "name": "LIONFI",
  "symbol": "LIONFI",
  "decimals": "9",
  "image": "https://cache.tonapi.io/imgproxy/6eYRdBfsM_GNPNyDaxYhtF4Jg4Wnl-Xb9spXmQQ2oPc/rs:fill:200:200:1/g:no/aHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMC5nc3RhdGljLmNvbS9pbWFnZXM_cT10Ym46QU5kOUdjUi1rSzFPVk4tUmRpSDJ2THAyZHBETnVzRWlWaDJDaHRBLUxnb3EwcFZXVUVvWnRTbWI1bmw0UzdHSiZzPTEw.webp",
  "description": "Memcoin"
}

**Comment by TonyDEv-lab** [comment]
@AsianMokaev It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
