### ISSUE TITLE
I HAVE LOSS MY MONEY😓

### ISSUE THREAD

**Issue by Asif101127** [tonkeeper/ton-assets#885]
Plzz give me 1 ton😭
My wallet address-
UQBNvaP-HESxawOZMFOCeIVegdnsqD8X1hbDFh_exr1LYzQJ
![Screenshot_20240717_021347_com ton_keeper](https://github.com/user-attachments/assets/32342bbd-9295-46d7-9872-308f67eda62e)

**Comment by Asif101127** [comment]
#791
Plzz give me ton😭😞
I have loss my Money and my Mind😥

**Comment by Mamad3426m** [comment]
مگه چی شده
