### ISSUE TITLE
Please add a token PLD

### ISSUE THREAD

**Issue by PalladiumVF** [tonkeeper/ton-assets#888]
Please add a token PLD

Address - EQDgGuB15VUI7wkJ9c5_tjQswWuePEtqTDXSHIYKMMSxx_2U

{
  "address": "0:e01ae075e55508ef0909f5ce7fb6342cc16b9e3c4b6a4c35d21c860a30c4b1c7",
  "name": "Palladium",
  "symbol": "PLD",
  "decimals": "9",
  "image": "https://cache.tonapi.io/imgproxy/4ez2G83IseL0owNyOb8i3KPKOmL0n5V8NjsSvDyc_eY/rs:fill:200:200:1/g:no/aHR0cHM6Ly9nbGViZXJtb24uZ2l0aHViLmlvL2xvZ28ucG5n.webp",
  "description": "Palladium Venture Foundation"
}

LP Token for PLD-pTON - EQA-9ryce3AOHQmOPhWnSl1IGkgfLolMcdKiHBvUYKZgAKHw

**Comment by Mahdirzai0095** [comment]
[](url)content/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks.md

**Comment by Mahdirzai0095** [comment]
> لطفا یک PLD توکن اضافه کنید
> 
> آدرس - EQDgGuB15VUI7wkJ9c5_tjQswWuePEtqTDXSHIYKMMSxx_2U
> 
> { "آدرس": "0:e01ae075e55508ef0909f5ce7fb6342cc16b9e3c4b6a4c35d21c860a30c4b1c7"، "نام": "پالادیوم"، "نماد": "PLD"، "9"، " [https.piio ": "decimals." imgproxy/4ez2G83IseL0owNyOb8i3KPKOmL0n5V8NjsSvDyc_eY/rs:fill:200:200:1/g:no/aHR0cHM6Ly9nbGViZXJtb24uZ2l0aHViLmlv](https://cache.tonapi.io/imgproxy/4ez2G83IseL0owNyOb8i3KPKOmL0n5V8NjsSvDyc_eY/rs:fill:200:200:1/g:no/aHR0cHM6Ly9nbGViZXJtb24uZ2l0aHViLmlvL2xvZ28ucG5n.webp) " p بنیاد سرمایه گذاری" }
> 
> توکن LP برای PLD-pTON - EQA-9ryce3AOHQmOPhWnSl1IGkgfLolMcdKiHBvUYKZgAKforks.md

> لطفا یک PLD توکن اضافه کنید
> 
> آدرس - EQDgGuB15VUI7wkJ9c5_tjQswWuePEtqTDXSHIYKMMSxx_2U
> 
> { "آدرس": "0:e01ae075e55508ef0909f5ce7fb6342cc16b9e3c4b6a4c35d21c860a30c4b1c7"، "نام": "پالدیوم"، "نماد": "PLD."، " PLD."، "9 ["](https://cache.tonapi.io/imgproxy/4ez2G83IseL0owNyOb8i3KPKOmL0n5V8NjsSvDyc_eY/rs:fill:200:200:1/g:no/aHR0cHM6Ly9nbGViZXJtb24uZ2l0aHViLmlvL2xvZ28ucG5n.webp) imgproxy/4ez2G83IseL0owNyOb8i3KPKOmL0n5V8NjsSvDyc_eY/rs : [fill:200:200:1/g:no/aHR0cHM6Ly9nbGViZXJtb24uZ2l0aHViLmlv](https://cache.tonapi.io/imgproxy/4ez2G83IseL0owNyOb8i3KPKOmL0n5V8NjsSvDyc_eY/rs:fill:200:200:1/g:no/aHR0cHM6Ly9nbGViZXJtb24uZ2l0aHViLmlvL2xvZ28ucG5n.webp) " }[](https://cache.tonapi.io/imgproxy/4ez2G83IseL0owNyOb8i3KPKOmL0n5V8NjsSvDyc_eY/rs:fill:200:200:1/g:no/aHR0cHM6Ly9nbGViZXJtb24uZ2l0aHViLmlvL2xvZ28ucG5n.webp)
> 
> توکن LP برای PLD-pTON - 
https://github.com/tonkeeper/ton-assets/issues/888#issue-2413217185
