### ISSUE TITLE
Lumber jack tokens 

### ISSUE THREAD

**Issue by Maxdemko** [tonkeeper/ton-assets#914]
Lumber jack game tokens

**Comment by Sweetmind300** [comment]
@Maxdemko 
Are you able to claim? 
kindly give more details on this issues.

**Comment by Maxdemko** [comment]
I claimed only 10% of the tokens into my ton keeper wallet. But it's showing that the tokens is not verified. Also I can't transfer it to my biconomy exchange. Please kindly help in rectifying the issue. Thanks

**Comment by Maxdemko** [comment]
No sir uptil now I can't transfer it to my biconomy exchange. The tokens is
still showing unverified tokens in the ton keeper.

**Comment by TonyDEv-lab** [comment]
@Maxdemko It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Sweetmind300** [comment]
@Maxdemko 
Thia issue will be review on pull request, beware of scam links to avoid losing your assets.
