### ISSUE TITLE
Please add TMONKEY Jetton

### ISSUE THREAD

**Issue by lacostenycoder** [tonkeeper/ton-assets#926]
PR is ready to go, this should be an easy one ? 
https://github.com/tonkeeper/ton-assets/pull/882

**Comment by Uffynn** [comment]
Yeah. There are no updates, because there is nobody running the TonKeeper wallet. They are not even answering on the tickets when you report an issue. And if somebody does answer, they do get it after 7+ days, saying something along the lines: 'we dont want to fix any of your issues, tough luck'.

**Comment by lacostenycoder** [comment]
@mr-tron thank you! Do you know if this effects why it still shows in Ton Keeper as `Unverified Token`?

![Screenshot 2024-10-24 132711](https://github.com/user-attachments/assets/2785612c-4fc8-41f5-a7ab-a052ec3ef26f)
