### ISSUE TITLE
I'm confused ?

### ISSUE THREAD

**Issue by jayp89** [tonkeeper/ton-assets#970]
I have a serious question for this community and ecosystem as a whole I have tried to commit to token to this repository more than four times it's not even looked at I can see pull requests that have come in way after me get responses at least a comment if I'm doing something wrong you can tell me or is it because it's a project from Africa ? So weird that I am teaching courses about web 3 and the future of wave 3 being based on ton and yet the one project that all my students are following so closely the one that they have a taken I cannot get even added to a simple repository here to be quite Frank this is not the only Platform on TON that's snubbed and ignored our requests they all have. The only platform that met with us were DYOR I guess Denis Solovev is the most decent founder 

Highly disappointing to be ignored by your favorite wallet on a chain

@mr-tron

**Comment by salateur** [comment]
The pull requests page will be reviewed more frequently than in the past. It really took some time and we will fix that. 
If you still find any questions and need help - feel free to open a new commit 
have a good day
