### ISSUE TITLE
Token Verification Request $DOSA 

### ISSUE THREAD

**Issue by eagleNC** [tonkeeper/ton-assets#980]
Token Name: DOSA BOMB 
Description: DOSA is making $TON degens, a safer place! 
Image URL: https://ibb.co/M7qQCxF
Contract Address: EQCSnmVQqlt-K4Seh5Jn7komypvkP1TjaS3oVM_K1BcJZ4NN
Symbol: $DOSA
Official CTO Website: https://dosa.army
Social Links: 
- X : x.com/ctodosaonton
- Telegram : t.me/dosatoncto
- Medium : dosaarmy.medium.com
- WhitePaper : dosa-army.gitbook.io 
- GetGems : getgems.io/dosaarmy

**Comment by Bhzd20** [comment]
Yes
